services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb-test
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro

volumes:
  mongo_data: